# Generated by Django 4.1 on 2022-11-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fonocontacto',
            field=models.CharField(default=0, max_length=12, verbose_name='contacto'),
            preserve_default=False,
        ),
    ]
