# Generated by Django 4.1 on 2022-11-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0002_producto_fonocontacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fonocontacto',
            new_name='contacto',
        ),
    ]
