# Generated by Django 4.1 on 2022-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0003_rename_fonocontacto_producto_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False, verbose_name='categoria_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('envio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='envio_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_producto',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='estado_id')),
                ('descripcion', models.CharField(max_length=20, verbose_name='descripcion')),
            ],
        ),
    ]
