# Generated by Django 4.1 on 2022-11-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0004_categoria_envio_estado_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loging.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='envio_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loging.envio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loging.estado_producto'),
            preserve_default=False,
        ),
    ]
